### ISSUE TITLE
The 3-d mandelbrot set is very blurry 

### ISSUE THREAD

**Issue by Cliche1998** [jonnyhyman/Chaos#2]
Hey,
The rendered graph is really blurry and I'm getting a length mismatch message for distance, azimut and elevation

![mandelbrot issue](https://user-images.githubusercontent.com/41783468/73436612-dd837700-4370-11ea-9c55-8f104252072e.png)

**Comment by TilBlechschmidt** [comment]
AFAIK the blurryness comes from the fact that by default the scene is rendered with 100x100x100 instead of 1000x1000x1000 voxels since live rendering is hugely resource intensive and not really possible at anything above a few frames per second even on high end machines. The blending of the voxels and probably AA too makes it look blurry because it is such a "low" spatial resolution.

**Comment by Cliche1998** [comment]
What would be the recommended hardware requirements to get something as close as what's shown in the veritasium video or the sample gif

**Comment by TilBlechschmidt** [comment]
I’m not sure if there even is a hardware configuration that could handle this in real time since the code isn’t multi-threaded AFAIK. The video and sample GIF have been rendered over probably multiple hours.

**Comment by Cliche1998** [comment]
I tweaked the parameters as you said, I put D = 700, I = 1000 and 0max = 16
I used real time frames and this is the best I got
The 3d view was still blurry
![image](https://user-images.githubusercontent.com/41783468/73447846-9c499200-4385-11ea-9642-e60958b4c13c.png)


I'll try and render it and create a .mov with it

**Comment by Shubh-Raj** [comment]
No such file or directory: './data/fractal_mandelbrot_data1000_iter1500_ovs16.npz'

This shows up when i change the data and try to run.

**Comment by jonnyhyman** [comment]
@TilBlechschmidt you hit it on the nose, thanks for your responses!
@Cliche1998, running at D=1000, I=1500, Omax=16 will reproduce the views seen in the gif and in the video. 

`D` represents the dimensions of each voxel
`I` represents the number of mandelbrot iterations
`Omax` represents the number of oversampling iterations. If you want a draft rendering I would suggest setting this to 1. Omax increases the render time exponentially. (scales ~ O^2.7)

The code utilizes `vispy` which uses the GPU and OpenGL to do the volume rendering, so technically it is multithreaded, just on the GPU not the CPU!

The data generation task can also be parallel processed by turning on parallel=True in the simulate function's `@numba.njit` decorator.

@Shubh-Raj this is because you need to turn on data generation. Look for the parameter generate=0 and change it to generate=1

**Comment by jonnyhyman** [comment]
The solution to making the 3D mandelbrot set less blurry is to increase the number of voxels; ie. set `D = 1000` or higher
