### ISSUE TITLE
Problem running python logistic_mandelbrot.py

### ISSUE THREAD

**Issue by somera** [jonnyhyman/Chaos#39]
I get this

```
$ python logistic_mandelbrot.py
Traceback (most recent call last):
  File "D:\python\examples\Chaos\logistic_mandelbrot.py", line 446, in <module>
    NEW_TRANSLUCENT_FRAG_SHADER = vispy.visuals.volume.FRAG_SHADER.format(
KeyError: '\n    // Create a pseudo-random number between 0 and 1'
```

running it on Windows.

**Comment by Gabor-Baranyi** [comment]
I tried logistic_mandelbrot.py on Linux today, using a fresh conda environment with python 3.7, latest version of other required packages mentioned in the README file and I received the same error message. 

The error is due to an update in vispy.visuals.volume code, which no longer contains FRAG_SHADER attribute. I checked requirements.txt for the project. It indicates to use an older version of vispy (vispy==0.6.4). Downgrading it to 0.6.4 solved the issue..

**Comment by somera** [comment]
> I tried logistic_mandelbrot.py on Linux today, using a fresh conda environment with python 3.7, latest version of other required packages mentioned in the README file and I received the same error message.
> 
> The error is due to an update in vispy.visuals.volume code, which no longer contains FRAG_SHADER attribute. I checked requirements.txt for the project. It indicates to use an older version of vispy (vispy==0.6.4). Downgrading it to 0.6.4 solved the issue.

Sorry for the late answer. Now I installed the right python and requirements version and it works.
